services:

  web-api:
    build: .
    container_name: digital-twin-api
    ports:
      - "8000:8000"
    volumes:
      # Mount entire app directory for hot reload
      - .:/app
      # Exclude cache directories
      - /app/__pycache__
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - HEYGEN_API_KEY=${HEYGEN_API_KEY}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - MAX_FILE_SIZE_MB=${MAX_FILE_SIZE_MB:-50}
      - TEMP_DIR=/app/temp
      - OUTPUT_DIR=/app/output
      - PYTHONUNBUFFERED=1  # Ensure stdout/stderr are unbuffered
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Override command for hot reload with optional debugger
    command: ["python", "-Xfrozen_modules=off", "-m", "uvicorn", "web_api:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/app", "--log-level", "info"]