services:
  web-api:
    build: .
    container_name: digital-twin-api
    ports:
      - "8000:8000"
    volumes:
      - ./temp:/app/temp
      - ./output:/app/output
      - ./personas:/app/personas
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - HEYGEN_API_KEY=${HEYGEN_API_KEY}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - MAX_FILE_SIZE_MB=${MAX_FILE_SIZE_MB:-50}
      - TEMP_DIR=/app/temp
      - OUTPUT_DIR=/app/output
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s